"""
@author: ManglerFTW
@title: ComfyI2I
"""

from . import ComfyI2I

WEB_DIRECTORY = "./js"
NODE_CLASS_MAPPINGS = ComfyI2I.NODE_CLASS_MAPPINGS
NODE_DISPLAY_NAME_MAPPINGS = ComfyI2I.NODE_DISPLAY_NAME_MAPPINGS
